### ISSUE TITLE
Feature request: list of all supported tld's with their prices

### ISSUE THREAD

**Issue by Duncank** [opendomainregistry/api_library#2]
This way we can create a domainchecker that autosuggests other valid TLD's and immediately display a price next to available domains.

**Comment by staticall** [comment]
Good day and thank you for your question!

We were discussing this for some time and we will add this for sure! But sorry, i can't say exact date yet, because this change will require new functionality in ODR API code itself and right now, we have new functionality almost ready for deployment.
I think we will add this near end of current month, but no promises yet, sorry! ) Hope it's ok with you!

P. S.: Thank you for pull request, by the way!

**Comment by Duncank** [comment]
Thanks for your reply and for approving my pull request! I'm looking forward to the new functionality you are talking about, great work!

**Comment by staticall** [comment]
Hello, @Duncank, hope you're having a good day! )

Just a small update - i pushed update with new example, "my-prices.php", which should request prices for your current billing plan (or any available to you billing plan).

Format of response looks like this:
[tld] => array(
  'create_domain' => '1.11',
  'transfer_domain' => '2.22',
),
...

Please note, that all prices are in EUR!

You can check latest available docs here - http://api.odrregistry.nl/docs/#billing-plan|get-items

Please note, right now, this improvement ONLY available at our staging, http://odrregistry.nl/
You can create free account there and check this script!
Update to live should be at the beginning of next week!

If you have any ideas/improvements, please feel free to say! :)

**Comment by Duncank** [comment]
Hi @staticall , everything is great here, I hope you're having a good day as well.

The update looks to be exactly what we needed! I'm going to implement this in the beginning of next week and will let you know my findings!

**Comment by Duncank** [comment]
Update: I've created a test call and registered for an account on the staging site yesterday afternoon, but I guess it has to be approved first. Can you do that?

I'm curious to see, when the call works, if the "you pay" prices are returned for the .tld's where I did not enter anything myself in the billing plan. This way I can create a future proof solution for new domains that are being added to ODR by doing something like price + 3 euro's.

**Comment by staticall** [comment]
For TLDs you didn't have records in the billing plan - no, they will not be present in the response, main reasons for it - to make response as short as possible and to prevent your subcustomers/subusers from seeing additional TLDs that you do not want to show them for some reason! Oh, by the way, by default, this example requests your personal billing plan for prices, but you can replace the `$billingPlanId` variable with ID for your custom billing plan, if you want to get info about it.

I've activated your profile on odrregistry, by the way, happy testing! :)

**Comment by Duncank** [comment]
Thanks for activating my account! It will be a tough job entering all the prices in the billing plan, but I understand your reasoning! I've tested the call with the staging API and that seems to work fine.

Any clue on when this will roll out to the production API?

**Comment by staticall** [comment]
Yes, believe me, i know, i created a lot of them and really sorry about that! I hope in the middle of december, i'll finish API support for billing plan management, create/edit/copy/delete, then it should be a breeze! Then you can just use your current billing plan and adjust the prices in one quick API request!

As for production installation, i hope we will install this update in the beginning of next week (so 28-29th of november) OR (and it's only because of invoices on 1st), on december, 5th.
But i will comment in this issue when we will finalize the date AND when we will actually install this on production! Hope it'll be helpful to you! )

**Comment by staticall** [comment]
@Duncank Hello! We decided to install update today-tomorrow (sorry, was away on weekend, didn't tell you earlier), but i, personally, recommend you to start using/testing it on wednesday, because it's a very big update and there might be some buggy stuff here and there (not proud of it, but live sometimes likes to act strangely)

**Comment by Duncank** [comment]
@staticall Thanks for the heads up! I'm completely familiar with weird behaviour of code on live servers, so don't worry about that. We're working with this API in a new product that is only live for our own company at this time, so no other users will be using it. I'll let you know if we find bugs.

**Comment by staticall** [comment]
@Duncank Thank you! :)
We did install the big update on live, seems good so far, so you can start checking it! Hope you'll not find any bugs! :)

**Comment by Duncank** [comment]
@staticall I've just implemented it and it works great! Thanks for your help!

**Comment by staticall** [comment]
@Duncank Hello, really sorry for this long delay

I've pushed an update to our staging environment, at http://odrregistry.nl/
You can check the updated docs here - http://api.odrregistry.nl/docs/#billing-plan|post-create
Examples/better integration for this repo will be pushed little later, we're testing this update now

How to use:
- All available sets/operations for customer you can check using this command: http://api.odrregistry.nl/docs/#billing-plan|get-available-sets
- After you prepared the data, you should send it in the following format:
```
[title] = Title of billing plan*
[description] = Description of billing plan*
[items] = array(
  [set] = array(
    [operation] = [price]
  )
)
```

* = required

Response will have:

```
[title] = Title of billing plan
[description] = Description of billing plan
[items] = array(
  [set] = array(
    [operation] = [price]
  )
)
[warnings] = array(
  [type] = [sets]
)
[error] = array(
  [type] = [setsOrMessage]
)
```

If you have any ideas on how to improve this, i will gladly hear them out! :) Hope you'll like this update!
