### ISSUE TITLE
DNSSEC response

### ISSUE THREAD

**Issue by githubbauman** [opendomainregistry/api_library#3]
When I do a  /domain/:domain/dnssec/ query I get back this response from the server:

HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Date: Thu, 28 Jun 2018 16:14:32 GMT
Server: Apache
Etc....

Other API calls give this something like this:

HTTP/1.1 200 OK
Date: Thu, 28 Jun 2018 16:14:32 GMT
Server: Apache
Etc....

The response has extra information and  an extra empty line!
In ODR.php (line 505) the response is split by \r\n\r\n
Because there is an extra empty line the response, $resultHeaders, $resultBody are filled with wrong data.

The keys are stored on the (test) server, that is going very well, but the response is not working with this Odr.php I think.

**Comment by staticall** [comment]
Hello!

Thank you for opening this issue!

Can you please answer a few questions:
- Where are you sending requests to, preferably full URL? http://api.odrregistry.nl/domain/:domain/dnssec/? Or you're using live environment with HTTPS?
- Am i understanding you correctly - you send PUT request to update DNSSEC and data is stored (aka, available in GET /domain/:domain/info operation), but response from PUT /domain/:domain/dnssec is empty/messed up?
- Can you tell me what domain you were using, so i can check out the logs?

I'm asking because HTTP/1.1 100 Continue seems like server response, not related to ODR code, so maybe it's server misconfiguration, which we should fix.

**Comment by githubbauman** [comment]
We use the test server with HTTP, URL is http://api.odrregistry.nl/domain/sociotech.nl/dnssec/
We use a PUT request, we check the update with the GUI at http://odrregistry.nl/panel/operations/ and it looks like the keys a stored.
The domain we use to test is sociotech.nl I did a DNSSEC update at 13:27.

The "HTTP/1.1 100 Continue" is a server response but that is perfect server behavior! The Curl you use in ODR.php adds automatically a "Expect: 100-continue header" when a PUT or POST is bigger than 1024 Bytes. With 2 DNSSEC keys in the PUT request I count >1600 Bytes.

The solution could be to instruct Curl (Odr.php) not to send the  Expect: 100-continue header.
In Odr.php I changed the _execute method.

Old:
foreach ($this->_headers as $k => $v) {
    $headers[] = $k .': '. $v;
}

New:
foreach ($this->_headers as $k => $v) {
    $headers[] = $k .': '. $v;
}
$headers[] = 'Expect:';

Very well explanation here about this problem:
https://gms.tf/when-curl-sends-100-continue.html

**Comment by githubbauman** [comment]
Solved!
